apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: go-ci
spec:
  arguments:
    parameters:
      - name: repo 
        value: https://github.com/kevinkowalew/go-api.git
      - name: workdir
        value: /go/src/github.com/kevinkowalew/go-api
      - name: version
        value: 0.3.1
      - name: imageName
        value: go-api
      - name: registry
        value: docker-registry:5000
  entrypoint: go-ci
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: go-ci
    inputs:
      parameters:
        - name:  repo
        - name:  workdir
        - name:  registry
        - name:  version
        - name:  imageName
    steps:
    - - name: build
        template: build
        arguments:
          parameters:
            - name: repo
              value: "{{inputs.parameters.repo}}"
            - name: workdir
              value: "{{inputs.parameters.workdir}}"
    - - name: test
        template: test
        arguments:
          parameters:
            - name: workdir
              value: "{{inputs.parameters.workdir}}"
    - - name: publish
        template: publish
        arguments:
          parameters:
            - name: workdir
              value: "{{inputs.parameters.workdir}}"
            - name: registry
              value: "{{inputs.parameters.registry}}"
            - name: version
              value: "{{inputs.parameters.version}}"
            - name: imageName
              value: "{{inputs.parameters.imageName}}"

  - name: build
    inputs:
      parameters:
        - name: repo
        - name: workdir
      artifacts:
      - name: code
        path: "{{inputs.parameters.workdir}}"
        git:
          repo: "{{inputs.parameters.repo}}"
    container:
      image: golang:1.8
      command: [sh, -c]
      args: ["
        cd {{inputs.parameters.workdir}} &&
        go build -o api .
      "]
      volumeMounts:
      - name: workdir
        mountPath: /go

  - name: test
    inputs:
      parameters:
        - name: workdir
    container:
      image: golang:1.8
      command: [sh, -c]
      args: ["
        cd {{inputs.parameters.workdir}};
        go test ./...
      "]
      volumeMounts:
      - name: workdir
        mountPath: /go

  - name: publish
    inputs:
      parameters:
        - name: workdir
        - name: registry
        - name: version
        - name: imageName
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
      - --context={{inputs.parameters.workdir}}
      - --dockerfile={{inputs.parameters.workdir}}/Dockerfile
      - --destination={{inputs.parameters.registry}}/{{inputs.parameters.imageName}}:{{inputs.parameters.version}}
      - --insecure
      volumeMounts:
      - name: workdir
        mountPath: /go
