apiVersion: v1
kind: Pod
metadata:
  name: busybox-debug
  labels:
    app: debug
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      while true; do
        echo "Pod is running. Use 'kubectl exec' to debug.";
        sleep 3600;
      done
    volumeMounts:
    - name: swaggerui-volume
      mountPath: /etc/swaggerui
  volumes:
  - name: swaggerui-volume
    persistentVolumeClaim:
      claimName: swaggerui
  restartPolicy: Always
