{
 "title": "APIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "API",
    "label": "API Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Response Codes (By Endpoint)",
   "type": "gauge",
   "description": "Response codes returned from all endpoints.  Format is {endpoint}.{",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode($API.api.response.codes.*.*.count, 4, 5)"
    }
   ]
  },
  {
   "title": "Uptime (In Seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($API.api.uptime.value, 'Seconds')"
    }
   ]
  },
  {
   "title": "Request Timing (In Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "aliasByNode($API.api.request.time.*, 4)"
    }
   ]
  }
 ]
}