apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kevinkowalew/argo-homelab
    path: helm
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
