apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github-ci-template
  namespace: argo
  uid: bb945531-d1c1-4fae-ab6c-b0fcb626bc64
  resourceVersion: '348747'
  generation: 2
  creationTimestamp: '2024-12-08T05:58:45Z'
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2024-12-08T06:01:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:workflows.argoproj.io/creator: {}
        f:spec: {}
spec:
  templates:
    - name: go-ci
      inputs:
        parameters:
          - name: repo
          - name: registry
          - name: version
          - name: image
      outputs: {}
      metadata: {}
      steps:
        - - name: build
            template: build
            arguments:
              parameters:
                - name: repo
                  value: '{{inputs.parameters.repo}}'
                - name: image
                  value: '{{inputs.parameters.image}}'
        - - name: test
            template: test
            arguments:
              parameters:
                - name: repo
                  value: '{{inputs.parameters.repo}}'
                - name: image
                  value: '{{inputs.parameters.image}}'
        - - name: publish
            template: publish
            arguments:
              parameters:
                - name: repo
                  value: '{{inputs.parameters.repo}}'
                - name: registry
                  value: '{{inputs.parameters.registry}}'
                - name: version
                  value: '{{inputs.parameters.version}}'
    - name: build
      inputs:
        parameters:
          - name: repo
          - name: image
        artifacts:
          - name: code
            path: '/workdir/{{inputs.parameters.repo}}'
            git:
              repo: 'https://github.com/{{inputs.parameters.repo}}.git'
              usernameSecret:
                name: git-creds
                key: username
              passwordSecret:
                name: git-creds
                key: password
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: '{{inputs.parameters.image}}'
        command:
          - sh
          - '-c'
        args:
          - 'cd /workdir/{{inputs.parameters.repo}} && make build'
        resources: {}
        volumeMounts:
          - name: workdir
            mountPath: /workdir
    - name: test
      inputs:
        parameters:
          - name: repo
          - name: image
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: '{{inputs.parameters.image}}'
        command:
          - sh
          - '-c'
        args:
          - 'cd /workdir/{{inputs.parameters.repo}}; make test'
        resources: {}
        volumeMounts:
          - name: workdir
            mountPath: /workdir
    - name: publish
      inputs:
        parameters:
          - name: repo
          - name: registry
          - name: version
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: gcr.io/kaniko-project/executor:latest
        args:
          - '--context=/workdir/{{inputs.parameters.repo}}'
          - '--dockerfile=/workdir/{{inputs.parameters.repo}}/Dockerfile'
          - '--destination={{inputs.parameters.registry}}/{{inputs.parameters.repo}}:{{inputs.parameters.version}}'
          - '--insecure'
        resources: {}
        volumeMounts:
          - name: workdir
            mountPath: /workdir
  entrypoint: go-ci
  arguments:
    parameters:
      - name: repo
        value: kevinkowalew/auth-server
      - name: version
        value: 0.0.3
      - name: registry
        value: homelab-docker-registry:5000
      - name: image
        value: golang:1.19
  volumeClaimTemplates:
    - metadata:
        name: workdir
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}

