apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/kevinkowalew/homelab-gitops
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
