argo-cd:
  namespaceOverride: "argo"
  crds:
    install: true
    keep: false
argo-workflows:
  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
  crds:
    install: true
    keep: false
  server:
    extraArgs: ["--auth-mode=server"]
