argo-cd:
  namespaceOverride: "argo"
  crds:
    install: true
    keep: false
argo-workflows:
  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
  crds:
    install: true
    keep: false
  server:
    extraArgs: ["--auth-mode=server"]
docker-registry:
  persistence:
    accessMode: 'ReadWriteOnce'
    enabled: true
    deleteEnabled: true
    size: 10Gi
    storageClass: 'local-path'
